# build.yml
---
name: build

on:
  workflow_call:
    inputs:
      aaxclean-version:
        type: string
        description: "Libation version number"
        required: true
      dotnet-version:
        type: string
        default: "10.x"
        description: ".NET version to target"

jobs:

  linux:
    strategy:
      matrix:
        architecture: [arm64, x64]
        include:
          - runner: ubuntu-22.04-arm
            architecture: arm64
          - runner: ubuntu-22.04
            architecture: x64
    uses: ./.github/workflows/build-linux.yml
    with:
      aaxclean-version: ${{ inputs.aaxclean-version }}
      dotnet-version: ${{ inputs.dotnet-version }}
      architecture: ${{ matrix.architecture }}
      runner: ${{ matrix.runner }}
      native: Native
      
  mac:
    strategy:
      matrix:
        architecture: [arm64, x64]
    uses: ./.github/workflows/build-mac.yml
    with:
      aaxclean-version: ${{ inputs.aaxclean-version }}
      dotnet-version: ${{ inputs.dotnet-version }}
      architecture: ${{ matrix.architecture }}
      native: Native
      
  windows:
    strategy:
      matrix:
        architecture: [x86, x64]
    uses: ./.github/workflows/build-windows.yml
    with:
      aaxclean-version: ${{ inputs.aaxclean-version }}
      dotnet-version: ${{ inputs.dotnet-version }}
      architecture: ${{ matrix.architecture }}